### ISSUE TITLE
macOS 上压缩的 zip 包无法识别

### ISSUE THREAD

**Issue by laplace-anon** [gramlabs-oss/mini-assets#4]
上传后查看挂载的卷后可发现解压后的文件路径为乱码，附件为可复现压缩包
[_albums-broken.zip](https://github.com/gramlabs-oss/mini-assets/files/13478721/_albums-broken.zip)

**Comment by Hentioe** [comment]
好的 感谢反馈 我晚点会试试。你在 macos 上用的什么压缩软件呢？自带的压缩功能吗？

**Comment by laplace-anon** [comment]
对，就自带的压缩功能，macOS 绝大多数人都用自带的

**Comment by Hentioe** [comment]
我已经修复相关错误。实际上你遇到的有两层错误，一是解压后文件夹名称乱码导致路径和 `Manifest.yaml` 中的对不上。二是你的 `Manifest.yaml` 包含一个不存在的图集，名为 `C酱です`（这可能是你的某次误操作造成的）。

在最新的 Policr Mini 更新中，已经兼容了你这种可能乱码的压缩包，并且处理了图集不存在时的错误。现在图集不存在会直接忽略（例如你的压缩包中的 `C酱です`）。控制台日志输出还会看到这样一条错误日志提醒你：

`[error] Scanning album images failed: [exception: %File.Error{reason: :enoent, path: "_assets/_albums/C酱です", action: "list directory"}]`

注意：这是 Policr Mini 的更新，不是这个生成器的。未来也有可能给生成器增加压缩功能，避免类似的乱码问题。

**Comment by Hentioe** [comment]
我已测试你的图集，如果使用网格验证要添加两个变量配置成合适的尺寸：
```
POLICR_MINI_BOT_GRID_CAPTCHA_INDI_WIDTH: 250                                                                                                                                            
POLICR_MINI_BOT_GRID_CAPTCHA_INDI_HEIGHT: 250 
```
效果非常完美：

![image](https://github.com/gramlabs-oss/mini-assets/assets/13946976/76702bc2-7624-4b61-a888-0de2811d35f2)

但由于你的图集中基本只有一个图片，它不适合网格验证（会生成一个非常显眼的单个数字的答案）。
